@startuml
    [*] -> working_directory
    working_directory -> staging_area : git add
    staging_area -> local_repo : git commit
    local_repo -> remote_repo : git push
    remote_repo -> [*]
@enduml