graph LR
    %% Автор
    A1[Пишет документ в локальной ветке]
    A2[Создаёт Merge Request]

    subgraph Автор
        A1 --> A2
    end

    %% Коллеги
    B1[Проводят ревью / согласование]

    subgraph Коллеги
        A2 --> B1
    end

    %% CI
    C1[Тестирование документации]
    C2[Сборка]

    subgraph CI
        B1 --> C1 --> C2
    end

    %% Публикация
    D1[Загрузка в портал / Confluence / Pages]

    subgraph Публикация
        C2 --> D1
    end
